parameters:
    env(LOCO_API_KEY): ''

translation_adapter_loco:
    httplug_client: httplug.client.loco
    index_parameter: 'id'
    projects:
        messages:
            api_key: '%env(LOCO_PROJECT_API_KEY)%'
            domains: ['messages', 'validators']
