version: '3'
services:
  mariadb:
    image: mariadb
    volumes:
      - .docker/data/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: taskrunner
      MYSQL_USER: taskrunner
      MYSQL_PASSWORD: taskrunner
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - 3306:3306

  sso:
    image: enabel/docker-sso
    volumes:
      - .docker/data/sso/metadata:/var/simplesamlphp/metadata
    ports:
      - 443:443

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: toor
    ports:
      - 8080:80
    links:
      - mariadb

  maildev:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025
