---
- name: Send notification message via Slack all options
  slack:
    token: "{{ slack_token }}"
    domain: "{{ slack_domain }}"
    msg: 'Server: {{ ansible_hostname }} | Deployed ! :trophy:'
    username: "{{ slack_headline }}"
    icon_url: "{{ slack_icon_url }}"
    channel: "{{ slack_channel }}"
    parse: 'none'
  delegate_to: localhost