---
- name: Send notification message via Slack all options
  slack:
    token: "{{ slack_token }}"
    domain: "{{ slack_domain }}"
    msg: 'Server: {{ ansible_hostname }} | Deploy a new version of [{{ ansistrano_git_repo }} | branch: {{ git_branch }}] :crossed_fingers: '
    username: "{{ slack_headline }}"
    icon_url: "{{ slack_icon_url }}"
    channel: "{{ slack_channel }}"
    parse: 'none'
  delegate_to: localhost
