$ANSIBLE_VAULT;1.1;AES256
34333038306430346136383132646165373065346232633565666239613862396164396437313036
6566326661616237376132313265643461356332663963390a643033306464643037396366303964
64346166343231623032643833666332383339353265343739386333633730323362633730356433
3833346632663839640a333138313735613137633838623363343061636635373233353337613661
61383237306537363537373234303561643936313132366230323037666166316536316133653537
38623439656663383464383263353238393631646330313262663231633130333639393164653433
39616565623031623733306438666462636466343464393034643634366566323631353430613563
39636230396165663862376662306538623731363965323366633235313130636665356336393334
39613433646466396438373833353437393666653262343036316634613461633831656634623561
63333562643730613263663865383662376262623861366265633130363732333365623336333435
32303435343632336665646539323635303939303034393535626135613231626564343539376232
36646636633666613332306133643832623431643434313338386161313130343165323763303738
35623433636465363932343935623130646132343662643233386235623037613362616339626334
33653765656630363831343035623766303263303565353564383038616463393333663236396665
32646266313931306439633931313466346266313538653230646664636436343037323665376337
33633835396531333566306338353762643066663336306464616436613964343662323735623261
62336530376365626439663632653863343737303933393033313164383237356137653563306136
33666237656535643438373036306362356536633130663362373234646666373232393234616363
35363631616436666533323837623764306136386264616263303739376537386236666463306338
62626334326330303338353730336464353831653363333863306239313731623332366337316164
61373436386131393261653538343565613939373063356435383665346436643037303165386138
31383662353261363739373365643964346232663337396438653035343038333631633935616161
303466663034623431353238636135643739
