---
project_deploy_dir: '/var/www/html'
host_server_name: 'taskrunner01.up.btcctb.net'
application_url: 'http://{{ host_server_name }}/'
application_env: 'prod'
host_server_vhost_file: '/etc/apache2/sites-enabled/000-default.conf'
database_root: '{{ vault_database_root }}'
database_root_password: '{{ vault_database_root_password }}'
git_branch: 'master'
symfony_secret: '{{ vault_symfony_secret }}'
php_path: '/opt/rh/rh-php72/root/usr/bin/php'
mailer_transport: 'smtp'
mailer_host: 'smtp.office365.com'
mailer_port: '587'
mailer_user: "{{ vault_mailer_user }}"
mailer_password: "{{ vault_mailer_password }}"
mailer_encryption: 'tls'
mailer_auth_mode: 'login'
sso_base_url: '{{ vault_sso_base_url }}'
sso_idp_x509: '{{ vault_sso_idp_x509 }}'
sso_sp_key: '{{ vault_sso_sp_key }}'
