---
vault_github_oauth_token: "a5ad48cb8ba660bc54663adfba2082dd7aef0084"
vault_slack_token: "T9JGNPP40/BBBH3NBLY/BERHRhjBnjUjbFKGTajJwVgd"
vault_slack_domain: "enabel-be-ict.slack.com"
vault_loco_api_key: "hlC6K8aC9DRzE6l9b2FE6N8RCxffYIEP8"
vault_deploy_key_public: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDnoMVKpR/RVQgGCo83LTIzv8QylCrr9+FvEcOiGV9oIwN4OKr3WkXUJ1QQ94RLEayZdNnTSa4s/r9vEEiHnJCbAC1Iznj5wBOLmzxeohQmyhI3ZzyCh7ug2U0HD2dXy7g0WMAcix2rtkUumgAJLc4TwhyWdNZxR54+YvHoQ3CzZtNrT+eN5GCC2/5rtA/75RN6uK+qwilO7vKh1IiOD0Hj73yxKue5L8y8w7wDlDS66D99XQTpuERvuiH9RpBYbnv9GpqDO2zZ7UsUvHcqkyB+lxT06KGXBM2ZziibiLZh1iLXx5XYCaCS8g/vluWdiyoQmj4T994KUd4k6s8B/LmF devuser@dlagae-xps'
vault_deploy_key_private: |
  b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn
  NhAAAAAwEAAQAAAQEA56DFSqUf0VUIBgqPNy0yM7/EMpQq6/fhbxHDohlfaCMDeDiq91pF
  1CdUEPeESxGsmXTZ00muLP6/bxBIh5yQmwAtSM54+cATi5s8XqIUJsoSN2c8goe7oNlNBw
  9nV8u4NFjAHIsdq7ZFLpoACS3OE8IclnTWcUeePmLx6ENws2bTa0/njeRggtv+a7QP++UT
  erivqsIpTu7yodSIjg9B4+98sSrnuS/MvMO8A5Q0uug/fV0E6bhEb7oh/UaQWG57/Rqagz
  ts2e1LFLx3KpMgfpcU9OihlwTNmc4om4i2YdYi18eV2AmgkvIP75blnYsqEJo+E/feClHe
  JOrPAfy5hQAAA8ijrnqEo656hAAAAAdzc2gtcnNhAAABAQDnoMVKpR/RVQgGCo83LTIzv8
  QylCrr9+FvEcOiGV9oIwN4OKr3WkXUJ1QQ94RLEayZdNnTSa4s/r9vEEiHnJCbAC1Iznj5
  wBOLmzxeohQmyhI3ZzyCh7ug2U0HD2dXy7g0WMAcix2rtkUumgAJLc4TwhyWdNZxR54+Yv
  HoQ3CzZtNrT+eN5GCC2/5rtA/75RN6uK+qwilO7vKh1IiOD0Hj73yxKue5L8y8w7wDlDS6
  6D99XQTpuERvuiH9RpBYbnv9GpqDO2zZ7UsUvHcqkyB+lxT06KGXBM2ZziibiLZh1iLXx5
  XYCaCS8g/vluWdiyoQmj4T994KUd4k6s8B/LmFAAAAAwEAAQAAAQB4+rnRUQmbVmRIc391
  /D86VDDvkgARG3k9f/PEWKhCRfdr9X0mkJnkQ15fNkh8xRB3XlbfSp6UlcH7CnA3lIjazG
  7ali0NlUsgIcaYTuNjlyuIkH1EWAyh6J2Y0GzTqG3fuXMt9WNb6mmb+4eFQ81c+Ifh9ciD
  hjqarydWftMAf/gRV96sQ1S/i7Gui1suCpz6fdtPJznRCZq93dXoGHyADBMpWMayrnc3Hg
  KjUqAzKHTlWpOgGx4PZ8xxYbKZrCLQ6UyEX2D8j/P1/r5QsOlXBkqfhbzHHkJXIpTu2m/s
  c1w8b3C7HgO8h35w8bjgLkDTXkhR6Bv14wOicE9hjNgJAAAAgQCPqP31R4Tjlj++Cw1Vz7
  duPHHXSUy6QwHngqLj5ZqC0wTNGYpFTx8MgwxkXwdl6TNEMhS6UJOEfU3q+qSMcPP3Nz89
  9aojT6xbhGlOg3eeiRVwMKHaAoe6EU/YPkGxOYrRlvwqpaVZQdoFvixXtJgX1LGdmZ2T0R
  Ba/XpbC6UNxwAAAIEA88SQgxCP7OV3/wdICJ1i4agIRCiV0VtXnV3Ns1wx3dbrN8inPHqW
  EYPwk7QJptK9AHFsAQteuiyA8IHcpaZ71XTM/tUqvD4QYWfhljinhl0mQ6n/vIMFeteSlg
  0z2PlYAOzo7zGXEYbLiSb314PkvU7AU1kq3RQhzUJroQprQ+sAAACBAPNAQiMb1gHTUxYY
  n7WhU23t818w2DMYDBgT9qZ7iw88rq/+jCJ2AoZ8BTUiZ5Js/ORjyqgJ2yG/6U5Acx2pFm
  FzQcQVPme8VDYE9xYjexNVNjsqB7hkq83KMr85Ral/n2DQ3F5iuosjsxdUvkXklj+DYT2y
  w+zrIHQpppRO60xPAAAAEmRldnVzZXJAZGxhZ2FlLXhwcw==
