$ANSIBLE_VAULT;1.1;AES256
61316632653738613465656165353762616437323431323730396361653231663330326463313066
6666336636343365363136666234663531313533313039320a333230313665396134613166663230
39346265356264386466646236303332333038636236346530363837656462323166393465333836
6466623935663435370a373065313062613238353131636364343834313739623264656430313330
3730
