easy_admin:
  site_name: 'Interfaces monitor'
  design:
#    brand_color: '#d81a1a'
  list:
    title: admin.label.list
    actions:
      - { name: 'new', icon: 'plus', label: admin.action.new }
      - { name: 'show', icon: 'search', label: admin.action.show }
      - { name: 'edit', icon: 'pencil', label: admin.action.edit }
      - { name: 'delete', icon: 'close', label: admin.action.delete }
      - 'export'
    max_results: 20
  formats:
    date:     'd/m/Y'
    time:     'H:i'
    datetime: 'd/m/Y H:i:s'
